services:
  backend:
    image: battletalk-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    volumes:
      - ./backend:/backend

  frontend:
    image: battletalk-frontend
    env_file:
      - frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3131:3131"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend