// src/utils/data-learn.ts
export const learnUnits = [
  {
    id: 1,
    order: 1,
    title: 'Basic Vocabulary',
    description: 'Learn essential words and phrases',
    lessons: [
      {
        id: 1,
        title: 'Greetings Video',
        challenges: [],
        completed: false,
        lessonType: 'VIDEO' as 'VIDEO',
      },
      {
        id: 2,
        title: 'Greetings',
        challenges: [{ id: 1 }, { id: 2 }],
        completed: false,
        lessonType: 'QUIZ' as 'QUIZ',
      },
      {
        id: 3,
        title: 'Numbers',
        challenges: [{ id: 3 }, { id: 4 }],
        completed: false,
        lessonType: 'QUIZ' as 'QUIZ',
      },
      {
        id: 4,
        title: 'Common Objects',
        challenges: [{ id: 5 }, { id: 6 }],
        completed: false,
        lessonType: 'QUIZ' as 'QUIZ',
      },
    ],
  },
  {
    id: 2,
    order: 2,
    title: 'Grammar Fundamentals',
    description: 'Understand basic sentence structures',
    lessons: [
      {
        id: 5,
        title: 'Present Tense Video',
        challenges: [],
        completed: false,
        lessonType: 'VIDEO' as 'VIDEO',
      },
      {
        id: 6,
        title: 'Present Tense',
        challenges: [{ id: 7 }, { id: 8 }],
        completed: false,
        lessonType: 'QUIZ' as 'QUIZ',
      },
      {
        id: 7,
        title: 'Pronouns',
        challenges: [{ id: 9 }, { id: 10 }],
        completed: false,
        lessonType: 'QUIZ' as 'QUIZ',
      },
      {
        id: 8,
        title: 'Articles',
        challenges: [{ id: 11 }, { id: 12 }],
        completed: false,
        lessonType: 'QUIZ' as 'QUIZ',
      },
    ],
  },
  {
    id: 3,
    order: 3,
    title: 'Conversation Skills',
    description: 'Practice real-life conversations',
    lessons: [
      {
        id: 9,
        title: 'Introducing Yourself Video',
        challenges: [],
        completed: false,
        lessonType: 'VIDEO' as 'VIDEO',
      },
      {
        id: 10,
        title: 'Introducing Yourself',
        challenges: [{ id: 13 }, { id: 14 }],
        completed: false,
        lessonType: 'QUIZ' as 'QUIZ',
      },
      {
        id: 11,
        title: 'Asking for Directions',
        challenges: [{ id: 15 }, { id: 16 }],
        completed: false,
        lessonType: 'QUIZ' as 'QUIZ',
      },
    ],
  },
  {
    id: 4,
    order: 4,
    title: 'Listening Practice',
    description: 'Improve your listening skills',
    lessons: [
      {
        id: 12,
        title: 'Daily Conversations Video',
        challenges: [],
        completed: false,
        lessonType: 'VIDEO' as 'VIDEO',
      },
      {
        id: 13,
        title: 'Daily Conversations',
        challenges: [],
        completed: false,
        lessonType: 'VIDEO' as 'VIDEO',
      },
      {
        id: 14,
        title: 'News Listening',
        challenges: [],
        completed: false,
        lessonType: 'VIDEO' as 'VIDEO',
      },
    ],
  },
];
